# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0254a415202f3c6640f2e5449705c476"
name = "Eco Fee Automator"
application_url = "https://eco-fee-automator.onrender.com"
embedded = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_cart_transforms,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
# This must match the OAuth callback URL we told Shopify in the Partner Dashboard
redirect_urls = [ "https://eco-fee-automator.onrender.com/auth/callback" ]

[app_preferences]
# Where merchants land if they click your app in the admin (weâ€™ll use the root for now)
url = "https://eco-fee-automator.onrender.com/"

[build]
automatically_update_urls_on_dev = true
