# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0254a415202f3c6640f2e5449705c476"
name = "Alberta Eco Fee"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_cart_transforms,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://example.com" ]

[app_preferences]
url = "https://example.com"

[build]
automatically_update_urls_on_dev = true
