api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "eco-fee-cart-transform"
type = "function"
uid = "8e62fc2a-7b1f-b90d-f97d-d63cf9b6bcf6421cdfce"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
