# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6b42cae57b24786788bb7183c7135783"
name = "Eco-Fee-Transformer"
application_url = "https://incomplete-cambridge-affiliates-consult.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  # App-level webhooks
  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://incomplete-cambridge-affiliates-consult.trycloudflare.com/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://incomplete-cambridge-affiliates-consult.trycloudflare.com/webhooks/app/scopes_update"

  # âœ… Mandatory compliance webhooks
  [[webhooks.subscriptions]]
  compliance_topics = [
    "customers/data_request",
    "customers/redact",
    "shop/redact",
  ]
  uri = "https://incomplete-cambridge-affiliates-consult.trycloudflare.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_cart_transforms"

[auth]
redirect_urls = [
  "https://incomplete-cambridge-affiliates-consult.trycloudflare.com/auth/callback",
  "https://incomplete-cambridge-affiliates-consult.trycloudflare.com/api/auth",
  "https://incomplete-cambridge-affiliates-consult.trycloudflare.com/auth/*",
]
